language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - hhvm

matrix:
  allow_failures:
    - php: 7.1
    - php: 7.2
    - php: hhvm

brefore_script:
  - travis_retry composer self-update
  - travis_retry composer update --prefer-stable --no-interaction --prefer-source

script: phpunit